added simple_jwt parameters to settings.py
aLEKS-e3/library-management-system pull request #4
Opened 2024-04-01 14:40 UTC by kabust

Forgot to add it initially, sorry guys 🙈

2024-04-01 14:47 UTC, aLEKS-e3 requested changes

2024-04-01 14:47 UTC, aLEKS-e3 commented on library_management/settings.py
> +    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
make access lifetime 1 day and refresh for 30 as for developing process)

2024-04-02 02:32 UTC, aLEKS-e3 approved these changes
nice!

2024-04-02 07:42 UTC, JohnnyWalker010 approved these changes

2024-04-02 07:44 UTC, merged