Implement borrowing list and detail endpoint
aLEKS-e3/library-management-system pull request #5
Opened 2024-04-01 16:08 UTC by motivated2

2024-04-01 16:44 UTC, kabust requested changes
Need to work a bit around serializers

2024-04-01 16:44 UTC, kabust commented on borrowings/admin.py
> +# Register your models here.
register borrowing model here to be able to see it in admin panel

2024-04-01 16:44 UTC, kabust commented on borrowings/serializers.py
> +    class Meta:
don't forget about blank line between classes

2024-04-01 16:44 UTC, kabust commented on borrowings/models.py
> +    borrow_date = models.DateField()
models.DateField(auto_now_add=True) to set todays date automatically

2024-04-01 16:44 UTC, kabust commented on borrowings/serializers.py
> +        fields = "__all__"
you should show book info here as well using the book serializer, otherwise, we'll see only the book's id, which is not pretty

2024-04-01 16:44 UTC, kabust commented on borrowings/serializers.py
> +        return representation
you can use a Book serializer to represent the book in this serializer, to_representation method is a bit complicated and redundant

2024-04-01 16:48 UTC, aLEKS-e3 requested changes

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/admin.py
> +# Register your models here.
register in admin

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/models.py
> +    borrow_date = models.DateField()
maybe it;s better to add `auto_now_add` parameter for `borrow_date`?

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/models.py
> +                f" {self.borrow_date} - {self.expected_return_date}")
add a blank line at the end of the file

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/serializers.py
> +    class Meta:
add a blank line between classes

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/tests/test_models.py
> +        borrowing.full_clean()
you need to use assert here

2024-04-01 16:48 UTC, aLEKS-e3 commented on borrowings/tests/test_models.py
> +        borrowing.full_clean()
and assert here as well

2024-04-02 02:36 UTC, aLEKS-e3 requested changes

2024-04-02 02:36 UTC, aLEKS-e3 commented on borrowings/models.py
> +                f" {self.borrow_date} - {self.expected_return_date}")
add a blank line at the end

2024-04-02 02:36 UTC, aLEKS-e3 commented on borrowings/serializers.py
> +    class Meta:
add a blank line between classes again)

2024-04-02 07:42 UTC, JohnnyWalker010 approved these changes

2024-04-02 08:01 UTC, aLEKS-e3 approved these changes
cool!

2024-04-02 08:26 UTC, kabust approved these changes
GJ!

2024-04-02 08:30 UTC, merged