Implement create borrowing endpoint
aLEKS-e3/library-management-system pull request #9
Opened 2024-04-02 08:54 UTC by motivated2

2024-04-02 13:43 UTC, aLEKS-e3 requested changes

2024-04-02 13:43 UTC, aLEKS-e3 commented on borrowings/serializers.py
> +    class Meta:
add a blank line

2024-04-02 13:43 UTC, aLEKS-e3 commented on borrowings/serializers.py
> +            user=self.context["request"].user
why didn't you make `self.request.user`?

2024-04-02 13:44 UTC, aLEKS-e3 requested changes

2024-04-02 13:44 UTC, aLEKS-e3 commented on borrowings/serializers.py
> +        return value
cover validation with a test

2024-04-02 16:13 UTC, kabust approved these changes
GJ!

2024-04-03 02:46 UTC, aLEKS-e3 requested changes

2024-04-03 02:46 UTC, aLEKS-e3 commented on borrowings/tests/test_serializers.py
> +        book = Book.objects.create(title='Test Book', author='Test Author', cover='HARD', inventory=0, daily_fee=10.0)
split this line it's too long

2024-04-03 02:46 UTC, aLEKS-e3 commented on borrowings/tests/test_serializers.py
> +        book = Book.objects.create(title='Test Book', author='Test Author', cover='HARD', inventory=10, daily_fee=10.0)
and this one

2024-04-03 03:28 UTC, aLEKS-e3 requested changes

2024-04-03 03:28 UTC, aLEKS-e3 commented on borrowings/views.py
> +        serializer.save(user=self.request.user)
add a blank line in the end

2024-04-03 07:45 UTC, aLEKS-e3 approved these changes

2024-04-03 10:02 UTC, merged